server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Backend application logs
  - job_name: backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: bookreader-backend
          __path__: /var/log/bookreader/backend/*.log

  # Nginx logs
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: bookreader-nginx
          __path__: /var/log/bookreader/nginx/*.log

  # PostgreSQL logs
  - job_name: postgres
    static_configs:
      - targets:
          - localhost
        labels:
          job: bookreader-postgres
          __path__: /var/log/bookreader/postgres/*.log

  # Redis logs
  - job_name: redis
    static_configs:
      - targets:
          - localhost
        labels:
          job: bookreader-redis
          __path__: /var/log/bookreader/redis/*.log

  # Celery worker logs
  - job_name: celery
    static_configs:
      - targets:
          - localhost
        labels:
          job: bookreader-celery
          __path__: /var/log/bookreader/celery/*.log

  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'