"""
Response schemas для Image generation endpoints.

Содержит Pydantic модели для:
- Статус системы генерации изображений
- Очередь генерации
- Статистика пользователя
- Информация об API провайдере

Version: Phase 1.2 Type Safety (2025-11-29)
"""

from pydantic import BaseModel, Field
from typing import Dict, List, Optional
from uuid import UUID


class QueueStats(BaseModel):
    """
    Статистика очереди генерации изображений.

    Используется в ImageGenerationStatusResponse.

    Attributes:
        pending_tasks: Задачи в очереди ожидания
        processing_tasks: Задачи в процессе выполнения
        completed_today: Выполнено задач сегодня
        failed_today: Провалено задач сегодня
    """

    pending_tasks: int = Field(ge=0, description="Tasks waiting in queue")
    processing_tasks: int = Field(ge=0, description="Currently processing")
    completed_today: int = Field(ge=0, description="Completed today")
    failed_today: int = Field(ge=0, description="Failed today")


class UserGenerationInfo(BaseModel):
    """
    Информация о квоте генерации для пользователя.

    Используется в ImageGenerationStatusResponse.

    Attributes:
        id: UUID пользователя
        can_generate: Может ли генерировать изображения сейчас
        remaining_quota: Оставшаяся квота на месяц (None = unlimited)
    """

    id: UUID
    can_generate: bool = Field(description="Can generate images now")
    remaining_quota: Optional[int] = Field(
        None,
        ge=0,
        description="Remaining quota this month, None if unlimited"
    )


class APIProviderInfo(BaseModel):
    """
    Информация об API провайдере генерации изображений.

    Используется в ImageGenerationStatusResponse.

    Attributes:
        provider: Название провайдера (Google Imagen 4, DALL-E, etc.)
        supported_formats: Поддерживаемые форматы (PNG, JPG, etc.)
        max_resolution: Максимальное разрешение
        estimated_time_per_image: Ориентировочное время генерации
    """

    provider: str = Field(default="Google Imagen 4", description="API provider name")
    supported_formats: List[str] = Field(
        default=["PNG"],
        description="Supported image formats"
    )
    max_resolution: str = Field(default="1024x1024", description="Max resolution")
    estimated_time_per_image: str = Field(
        default="5-15 seconds",
        description="Estimated generation time"
    )


class ImageGenerationStatusResponse(BaseModel):
    """
    Полный статус системы генерации изображений.

    Используется в GET /api/v1/images/generation/status.

    Включает:
    - Статус сервиса (operational, degraded, down)
    - Статистику очереди генерации
    - Информацию о квоте пользователя
    - Информацию об API провайдере

    Attributes:
        status: Состояние сервиса
        queue_stats: Статистика очереди
        user_info: Информация о пользователе
        api_info: Информация об API провайдере
    """

    status: str = Field(
        default="operational",
        description="Service status: operational | degraded | down"
    )
    queue_stats: QueueStats
    user_info: UserGenerationInfo
    api_info: APIProviderInfo


class UserImageStatsResponse(BaseModel):
    """
    Статистика генерации изображений пользователя.

    Используется в GET /api/v1/images/user/stats.

    Подсчитывает:
    - Общее количество сгенерированных изображений
    - Общее количество найденных описаний
    - Разбивку по типам описаний

    Attributes:
        total_images_generated: Всего сгенерировано изображений
        total_descriptions_found: Всего найдено описаний
        images_by_type: Количество изображений по типам (LOCATION, CHARACTER, etc.)
    """

    total_images_generated: int = Field(
        ge=0,
        description="Total images generated by user"
    )
    total_descriptions_found: int = Field(
        ge=0,
        description="Total descriptions extracted from books"
    )
    images_by_type: Dict[str, int] = Field(
        default_factory=dict,
        description="Images count by description type (LOCATION, CHARACTER, ATMOSPHERE)"
    )


class ImageGenerationSuccessResponse(BaseModel):
    """
    Response для успешной генерации изображения.

    Используется в POST /api/v1/images/generate/description/{description_id}.

    Attributes:
        image_id: UUID сгенерированного изображения
        description_id: UUID описания
        image_url: URL изображения
        generation_time: Время генерации в секундах
        status: Статус генерации (completed)
        created_at: ISO timestamp создания
        message: Сообщение об успехе
    """

    image_id: UUID = Field(description="Generated image ID")
    description_id: UUID = Field(description="Source description ID")
    image_url: str = Field(description="URL of generated image")
    generation_time: float = Field(ge=0.0, description="Generation time in seconds")
    status: str = Field(default="completed", description="Generation status")
    created_at: str = Field(description="ISO timestamp of creation")
    message: str = Field(default="Image generated successfully")


# ============================================================================
# EXPORTS
# ============================================================================

__all__ = [
    "QueueStats",
    "UserGenerationInfo",
    "APIProviderInfo",
    "ImageGenerationStatusResponse",
    "UserImageStatsResponse",
    "ImageGenerationSuccessResponse",
]
