"""add_reading_location_cfi_field

Revision ID: 8ca7de033db9
Revises: 9ddbcaab926e
Create Date: 2025-10-19 23:48:18.273484+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ca7de033db9'
down_revision: Union[str, None] = '9ddbcaab926e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_settings_category', table_name='admin_settings')
    op.drop_index('ix_admin_settings_is_active', table_name='admin_settings')
    op.drop_index('ix_admin_settings_key', table_name='admin_settings')
    op.drop_table('admin_settings')
    op.add_column('reading_progress', sa.Column('reading_location_cfi', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading_progress', 'reading_location_cfi')
    op.create_table('admin_settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('value_string', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('value_int', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_float', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('value_bool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admin_settings_pkey'),
    sa.UniqueConstraint('category', 'key', name='admin_settings_category_key_key')
    )
    op.create_index('ix_admin_settings_key', 'admin_settings', ['key'], unique=False)
    op.create_index('ix_admin_settings_is_active', 'admin_settings', ['is_active'], unique=False)
    op.create_index('ix_admin_settings_category', 'admin_settings', ['category'], unique=False)
    # ### end Alembic commands ###