"""Add user_id to generated_images

Revision ID: 66ac03dc5ab6
Revises: 4de5528c20b4
Create Date: 2025-08-23 23:00:54.335208+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ac03dc5ab6'
down_revision: Union[str, None] = '4de5528c20b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_images', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_generated_images_user_id'), 'generated_images', ['user_id'], unique=False)
    op.create_foreign_key(None, 'generated_images', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generated_images', type_='foreignkey')
    op.drop_index(op.f('ix_generated_images_user_id'), table_name='generated_images')
    op.drop_column('generated_images', 'user_id')
    # ### end Alembic commands ###