"""Add reading_sessions table for detailed reading analytics

Revision ID: bf69a2347ac9
Revises: f1a2b3c4d5e6
Create Date: 2025-10-27 19:22:41.327120+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf69a2347ac9'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('start_position', sa.Integer(), nullable=False),
    sa.Column('end_position', sa.Integer(), nullable=False),
    sa.Column('pages_read', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reading_sessions_active', 'reading_sessions', ['user_id', 'is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_reading_sessions_book', 'reading_sessions', ['book_id', 'started_at'], unique=False)
    op.create_index('idx_reading_sessions_user_started', 'reading_sessions', ['user_id', 'started_at'], unique=False)
    op.create_index('idx_reading_sessions_weekly', 'reading_sessions', ['user_id', 'started_at', 'duration_minutes'], unique=False)
    op.create_index(op.f('ix_reading_sessions_book_id'), 'reading_sessions', ['book_id'], unique=False)
    op.create_index(op.f('ix_reading_sessions_id'), 'reading_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_reading_sessions_is_active'), 'reading_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_reading_sessions_started_at'), 'reading_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_reading_sessions_user_id'), 'reading_sessions', ['user_id'], unique=False)
    # NOTE: НЕ удаляем критически важные performance индексы из миграции f1a2b3c4d5e6
    # Они создавались вручную и не отражены в моделях, но необходимы для производительности:
    # - idx_books_user_created
    # - idx_books_user_unparsed
    # - idx_chapters_book_number
    # - idx_descriptions_chapter_priority
    # - idx_generated_images_description
    # - idx_images_status_created
    # - idx_reading_progress_last_read
    # - idx_reading_progress_user_book
    # - idx_subscriptions_user_status
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Откат миграции - удаление таблицы reading_sessions.

    NOTE: НЕ пересоздаем performance индексы, т.к. они не были удалены в upgrade()
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: НЕ пересоздаем критические индексы (они не удалялись)

    # Удаляем индексы reading_sessions
    op.drop_index(op.f('ix_reading_sessions_user_id'), table_name='reading_sessions')
    op.drop_index(op.f('ix_reading_sessions_started_at'), table_name='reading_sessions')
    op.drop_index(op.f('ix_reading_sessions_is_active'), table_name='reading_sessions')
    op.drop_index(op.f('ix_reading_sessions_id'), table_name='reading_sessions')
    op.drop_index(op.f('ix_reading_sessions_book_id'), table_name='reading_sessions')
    op.drop_index('idx_reading_sessions_weekly', table_name='reading_sessions')
    op.drop_index('idx_reading_sessions_user_started', table_name='reading_sessions')
    op.drop_index('idx_reading_sessions_book', table_name='reading_sessions')
    op.drop_index('idx_reading_sessions_active', table_name='reading_sessions', postgresql_where=sa.text('is_active = true'))

    # Удаляем таблицу reading_sessions
    op.drop_table('reading_sessions')
    # ### end Alembic commands ###