"""add scroll_offset_percent to reading_progress

Revision ID: e94cab18247f
Revises: 8ca7de033db9
Create Date: 2025-10-20 23:28:57.302995+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e94cab18247f'
down_revision: Union[str, None] = '8ca7de033db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_progress', sa.Column('scroll_offset_percent', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading_progress', 'scroll_offset_percent')
    # ### end Alembic commands ###