"""add_feature_flags_table

Revision ID: 72f14c0d1a64
Revises: enum_checks_2025
Create Date: 2025-11-22 21:37:54.590984+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f14c0d1a64'
down_revision: Union[str, None] = 'enum_checks_2025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Unique flag name (e.g., 'USE_NEW_NLP_ARCHITECTURE')"),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether the flag is enabled'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Flag category (nlp, parser, images, system, experimental)'),
    sa.Column('description', sa.Text(), nullable=True, comment="Human-readable description of the flag's purpose"),
    sa.Column('default_value', sa.Boolean(), nullable=False, comment='Default value (fallback if flag not found)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_category'), 'feature_flags', ['category'], unique=False)
    op.create_index(op.f('ix_feature_flags_enabled'), 'feature_flags', ['enabled'], unique=False)
    op.create_index(op.f('ix_feature_flags_id'), 'feature_flags', ['id'], unique=False)
    op.create_index(op.f('ix_feature_flags_name'), 'feature_flags', ['name'], unique=True)
    op.drop_index('idx_books_metadata_gin', table_name='books', postgresql_using='gin')
    op.drop_index('idx_books_user_created', table_name='books')
    op.drop_index('idx_books_user_unparsed', table_name='books', postgresql_where='(is_parsed = false)')
    op.drop_index('idx_chapters_book_number', table_name='chapters')
    op.drop_index('idx_descriptions_chapter_priority', table_name='descriptions')
    op.drop_index('idx_generated_images_description', table_name='generated_images')
    op.drop_index('idx_generated_images_moderation_gin', table_name='generated_images', postgresql_using='gin')
    op.drop_index('idx_generated_images_params_gin', table_name='generated_images', postgresql_using='gin')
    op.drop_index('idx_images_status_created', table_name='generated_images')
    op.alter_column('reading_progress', 'scroll_offset_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_reading_progress_last_read', table_name='reading_progress')
    op.drop_index('idx_reading_progress_user_book', table_name='reading_progress')
    op.drop_index('idx_reading_sessions_book_stats', table_name='reading_sessions')
    op.drop_index('idx_reading_sessions_cleanup', table_name='reading_sessions')
    op.drop_index('idx_reading_sessions_user_active_partial', table_name='reading_sessions', postgresql_where='(is_active = true)')
    op.drop_index('idx_reading_sessions_weekly_stats', table_name='reading_sessions')
    op.drop_index('idx_subscriptions_user_status', table_name='subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_subscriptions_user_status', 'subscriptions', ['user_id', 'status'], unique=False)
    op.create_index('idx_reading_sessions_weekly_stats', 'reading_sessions', ['user_id', 'started_at', 'duration_minutes', 'is_active'], unique=False)
    op.create_index('idx_reading_sessions_user_active_partial', 'reading_sessions', ['user_id'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('idx_reading_sessions_cleanup', 'reading_sessions', ['is_active', 'ended_at', 'started_at'], unique=False)
    op.create_index('idx_reading_sessions_book_stats', 'reading_sessions', ['book_id', 'started_at', 'is_active'], unique=False)
    op.create_index('idx_reading_progress_user_book', 'reading_progress', ['user_id', 'book_id'], unique=False)
    op.create_index('idx_reading_progress_last_read', 'reading_progress', ['user_id', 'last_read_at'], unique=False)
    op.alter_column('reading_progress', 'scroll_offset_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=False)
    op.create_index('idx_images_status_created', 'generated_images', ['status', 'created_at'], unique=False)
    op.create_index('idx_generated_images_params_gin', 'generated_images', ['generation_parameters'], unique=False, postgresql_using='gin')
    op.create_index('idx_generated_images_moderation_gin', 'generated_images', ['moderation_result'], unique=False, postgresql_using='gin')
    op.create_index('idx_generated_images_description', 'generated_images', ['description_id'], unique=False)
    op.create_index('idx_descriptions_chapter_priority', 'descriptions', ['chapter_id', 'priority_score'], unique=False)
    op.create_index('idx_chapters_book_number', 'chapters', ['book_id', 'chapter_number'], unique=False)
    op.create_index('idx_books_user_unparsed', 'books', ['user_id', 'is_parsed'], unique=False, postgresql_where='(is_parsed = false)')
    op.create_index('idx_books_user_created', 'books', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_books_metadata_gin', 'books', ['book_metadata'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_feature_flags_name'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_id'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_enabled'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_category'), table_name='feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###