# Grafana datasource provisioning для Prometheus
# Автоматически настраивает Prometheus как источник данных при старте Grafana

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
    version: 1
